version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "5432:5432"
